FROM apache/airflow:2.8.1

USER airflow

COPY requirements.txt .

ARG AIRFLOW_VERSION=2.8.1
ARG PYTHON_VERSION=3.8

RUN pip install --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt" \
    -r requirements.txt
